# Generated by Django 4.2.13 on 2026-06-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESGAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company name')),
                ('source_type', models.CharField(choices=[('file', 'Document'), ('text', 'Text')], default='file', max_length=8)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('environmental_score', models.PositiveSmallIntegerField(default=0)),
                ('social_score', models.PositiveSmallIntegerField(default=0)),
                ('governance_score', models.PositiveSmallIntegerField(default=0)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('result_json', models.JSONField(default=dict)),
                ('language', models.CharField(default='uz', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ESG analysis',
                'verbose_name_plural': 'ESG analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
