# Generated by Django 4.2.13 on 2026-07-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company name')),
                ('source_type', models.CharField(choices=[('file', 'Document'), ('text', 'Text')], default='file', max_length=8)),
                ('filenames', models.JSONField(blank=True, default=list)),
                ('verdict', models.CharField(choices=[('green', 'Green'), ('not_green', 'Not green'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=12)),
                ('verdict_title', models.CharField(blank=True, max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('environmental_score', models.PositiveSmallIntegerField(default=0)),
                ('social_score', models.PositiveSmallIntegerField(default=0)),
                ('governance_score', models.PositiveSmallIntegerField(default=0)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('result_json', models.JSONField(default=dict)),
                ('language', models.CharField(default='uz', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Client name')),
                ('stir', models.CharField(blank=True, max_length=32, verbose_name='Tax ID (STIR)')),
                ('industry', models.CharField(blank=True, max_length=128, verbose_name='Industry')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='Region')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ESGAnalysis',
        ),
        migrations.AddField(
            model_name='analysis',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='dashboard.client', verbose_name='Client'),
        ),
    ]
