# Generated by Django 4.2.13 on 2026-07-13 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_analysis_client_delete_esganalysis_analysis_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='kind',
            field=models.CharField(choices=[('bank', 'Bank verdict'), ('readiness', 'Entrepreneur readiness')], db_index=True, default='bank', max_length=12),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
