# Generated by Django 4.2.13 on 2026-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_analysis_created_by_analysis_kind_client_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Contract ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_product',
            field=models.CharField(blank=True, max_length=128, verbose_name='Credit product'),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_purpose',
            field=models.CharField(blank=True, max_length=255, verbose_name='Credit purpose'),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Credit rate, %'),
        ),
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(blank=True, max_length=8, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='client',
            name='field',
            field=models.CharField(blank=True, max_length=128, verbose_name='Field'),
        ),
        migrations.AddField(
            model_name='client',
            name='green_direction',
            field=models.CharField(blank=True, max_length=128, verbose_name='Green direction'),
        ),
        migrations.AddField(
            model_name='client',
            name='green_mark',
            field=models.CharField(blank=True, max_length=32, verbose_name='Green mark'),
        ),
        migrations.AddField(
            model_name='client',
            name='region_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Region code'),
        ),
        migrations.AddField(
            model_name='client',
            name='sector',
            field=models.CharField(blank=True, max_length=128, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='client',
            name='segment',
            field=models.CharField(blank=True, max_length=64, verbose_name='Segment'),
        ),
    ]
