# Generated by Django 4.2.13 on 2026-07-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('bank', 'Bank xodimi'), ('entrepreneur', 'Tadbirkor')], db_index=True, default='bank', max_length=16, verbose_name='Rol'),
        ),
    ]
