# Generated by Django 6.0.3 on 2026-05-09 10:58

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Slug')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Asosiy rasm')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Qisqa matn')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Matn')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('is_published', models.BooleanField(default=False, verbose_name='Chop etilgan')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Chop etilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
                'ordering': ['-published_at'],
            },
        ),
    ]
