# Generated by Django 6.0.3 on 2026-05-09 12:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_category_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qisqa matn'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_ru',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qisqa matn'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_uz',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qisqa matn'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
